#!/usr/bin/env python3
"""Generate machine-readable design tokens from the DESIGN.md frontmatter.

Each design system's DESIGN.md carries its full palette, type, spacing and
component spec in YAML frontmatter. That frontmatter is the source of truth;
this script is the only thing allowed to turn it into consumable artefacts, so
that no site ever hand-transcribes a hex.

Outputs, one pair per system, into tokens/:
    <slug>.json   the frontmatter verbatim, plus a _meta block
    <slug>.css    CSS custom properties under :root (and a light-mode block)

Also writes tokens/index.json listing every system and its doc version.

Usage:
    python3 tools/build_tokens.py            # write tokens/
    python3 tools/build_tokens.py --check    # fail if tokens/ is stale
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("pyyaml is required: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS_DIR = ROOT / "tokens"

# slug -> path of the DESIGN.md that owns it
SYSTEMS = {
    "sqrdao": "DESIGN.md",
    "youai": "youai/DESIGN.md",
    "summit": "summit/DESIGN.md",
    "danang-hub": "danang-hub/DESIGN.md",
    "empower-residency": "empower-residency/DESIGN.md",
}

# Top-level frontmatter keys that become CSS custom properties, and the prefix
# each one gets. Keys not listed here stay in the JSON but are not emitted as
# CSS (they are metadata, not values a stylesheet can use).
CSS_SECTIONS = {
    "colors": "color",
    "secondary-accent": "secondary-accent",
    "spacing": "spacing",
    "breakpoints": "breakpoint",
    "typography": "font",
    "components": "component",
}

# Emitted into the light-mode block rather than :root: one `<section>-light` key
# per emitted section, derived rather than hand-listed. A hand-maintained list is
# the same trap the frozen-at-dark guard exists to catch — a new
# `typography-light` would be dropped on the floor and a light-mode consumer
# reading one of its variables would silently get the dark value.
CSS_LIGHT_SECTIONS = {f"{key}-light": prefix for key, prefix in CSS_SECTIONS.items()}

# Prose fields that document a token for a human. They belong in the JSON and in
# DESIGN.md, never in a stylesheet.
PROSE_KEYS = {"note", "notes", "description", "comment"}

# Hex literals inside any emitted value, so the build can tell when a component
# alias has hard-coded a colour that light mode re-points.
HEX = re.compile(r"#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b")

# A value like "<pixel-display>" is a placeholder the brand has not resolved yet.
# Emitting it live would hand consumers a silently broken font stack, so it ships
# commented out and the build reports it.
PLACEHOLDER = re.compile(r"<[^>]+>")

BANNER = "/* GENERATED by tools/build_tokens.py from {src}. Do not edit by hand. */"


def kebab(name: str) -> str:
    """fontWeight -> font-weight, surface-alt -> surface-alt."""
    return re.sub(r"(?<!^)(?=[A-Z])", "-", str(name)).lower()


def read_frontmatter(path: pathlib.Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path}: no YAML frontmatter")
    end = text.find("\n---", 4)
    if end == -1:
        raise ValueError(f"{path}: unterminated frontmatter")
    data = yaml.safe_load(text[4:end])
    if not isinstance(data, dict):
        raise ValueError(f"{path}: frontmatter is not a mapping")
    return data


def flatten(prefix: str, value, out: list[tuple[str, str]]) -> None:
    """Walk a frontmatter subtree into (css-var-name, value) pairs."""
    if isinstance(value, dict):
        for key, sub in value.items():
            if str(key).lower() in PROSE_KEYS:
                continue
            flatten(f"{prefix}-{kebab(key)}", sub, out)
    elif isinstance(value, list):
        if all(not isinstance(item, (dict, list)) for item in value):
            for index, item in enumerate(value):
                out.append((f"{prefix}-{index}", str(item)))
        # lists of mappings have no sensible CSS representation; JSON keeps them
    elif value is not None:
        out.append((prefix, str(value)))


def css_pairs(data: dict, sections: dict[str, str]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for key, prefix in sections.items():
        if key in data:
            flatten(f"--{prefix}", data[key], pairs)
    return pairs


def emit(lines: list[str], pairs: list[tuple[str, str]], warnings: list[str], slug: str) -> None:
    for name, value in pairs:
        if PLACEHOLDER.search(value):
            warnings.append(f"{slug}: {name} holds an unresolved placeholder ({value})")
            lines.append(f"  /* UNRESOLVED, see DESIGN.md: {name}: {value}; */")
        else:
            lines.append(f"  {name}: {value};")


def frozen_at_dark(
    root: list[tuple[str, str]],
    light: list[tuple[str, str]],
    slug: str,
    warnings: list[str],
) -> None:
    """Warn about aliases that light mode cannot reach.

    A `--component-*` value that hard-codes a hex the light block re-points is a
    dark-only value: the light block never mentions that variable, so a consumer
    in light mode gets the dark colour. That is how a #1A1A1A card ended up on a
    #FAF9F6 page. The fix is a `components-light` override, not a doc note.
    """
    if not light:
        return
    light_values = dict(light)
    # dark hex -> the palette variables that carry it that light mode re-points.
    # One hex can serve several roles: #FFC700 is both --color-accent (constant)
    # and --color-gold-ink (darkens), #181818 both --color-on-accent (constant)
    # and --color-surface-alt (moves). A hard-coded hex names none of them, so
    # the build cannot tell which role was meant — if *any* carrier moves, the
    # alias may be frozen at dark and is reported. Silencing it is a one-line
    # `components-light` override, which is also the answer when the role that
    # moves is the one intended.
    moved: dict[str, list[str]] = {}
    for name, value in root:
        if not name.startswith("--color-") or not HEX.fullmatch(value.strip()):
            continue
        key = value.strip().lower()
        replacement = light_values.get(name)
        if replacement and replacement.strip().lower() != key:
            moved.setdefault(key, []).append(name)

    for name, value in root:
        if name.startswith("--color-") or name in light_values:
            continue
        for found in HEX.findall(value):
            if found.lower() in moved:
                warnings.append(
                    f"{slug}: {name} hard-codes {found} "
                    f"({', '.join(moved[found.lower()])} re-points it in light mode) "
                    f"but has no light-mode override"
                )
                break


def render_css(slug: str, src: str, data: dict, warnings: list[str]) -> str:
    lines = [BANNER.format(src=src), ""]
    lines.append(f"/* {data.get('design-system', slug)} v{data.get('version', '?')} */")
    root = css_pairs(data, CSS_SECTIONS)
    lines.append(":root {")
    emit(lines, root, warnings, slug)
    lines.append("}")

    # A `*-light` key that is not the counterpart of an emitted section (a typo,
    # or a section CSS_SECTIONS does not carry) reaches no stylesheet at all.
    # Silence there reads as "the override took".
    for key in data:
        if str(key).endswith("-light") and key not in CSS_LIGHT_SECTIONS:
            warnings.append(
                f"{slug}: frontmatter section {key} is not the light-mode "
                f"counterpart of any emitted section and reaches no stylesheet"
            )

    light = css_pairs(data, CSS_LIGHT_SECTIONS)
    frozen_at_dark(root, light, slug, warnings)
    if light:
        lines.append("")
        lines.append("/* Light mode. Warm neutrals, not a cool inversion of dark mode. */")
        lines.append('[data-theme="light"] {')
        emit(lines, light, warnings, slug)
        lines.append("}")

    return "\n".join(lines) + "\n"


def render_json(slug: str, src: str, data: dict) -> str:
    payload = {
        "_meta": {
            "generated_by": "tools/build_tokens.py",
            "source": src,
            "slug": slug,
            "warning": "Generated from DESIGN.md frontmatter. Do not edit by hand.",
        },
        **data,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def build(warnings: list[str]) -> dict[pathlib.Path, str]:
    """Return the full set of files this build would write."""
    files: dict[pathlib.Path, str] = {}
    index = []

    for slug, rel in SYSTEMS.items():
        path = ROOT / rel
        if not path.exists():
            raise FileNotFoundError(f"missing design doc: {rel}")
        data = read_frontmatter(path)
        files[TOKENS_DIR / f"{slug}.json"] = render_json(slug, rel, data)
        files[TOKENS_DIR / f"{slug}.css"] = render_css(slug, rel, data, warnings)
        index.append(
            {
                "slug": slug,
                "name": data.get("design-system", slug),
                "version": data.get("version"),
                "source": rel,
                "json": f"tokens/{slug}.json",
                "css": f"tokens/{slug}.css",
            }
        )

    files[TOKENS_DIR / "index.json"] = (
        json.dumps(
            {
                "_meta": {
                    "generated_by": "tools/build_tokens.py",
                    "warning": "Generated from DESIGN.md frontmatter. Do not edit by hand.",
                },
                "systems": index,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n"
    )
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if tokens/ differs from what would be generated",
    )
    args = parser.parse_args()

    warnings: list[str] = []
    files = build(warnings)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)

    if args.check:
        stale = [
            path
            for path, content in files.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        # Dotfiles are skipped: this repo lives on a filesystem that sprays
        # AppleDouble "._name" siblings next to every file, and they are gitignored.
        extra = [
            p
            for p in sorted(TOKENS_DIR.glob("*"))
            if p.is_file()
            and p not in files
            and not p.name.startswith(".")
            and p.name != "README.md"
        ]
        if stale or extra:
            for path in stale:
                print(f"stale:  {path.relative_to(ROOT)}", file=sys.stderr)
            for path in extra:
                print(f"orphan: {path.relative_to(ROOT)}", file=sys.stderr)
            print(
                "\ntokens/ is out of date. Run: python3 tools/build_tokens.py",
                file=sys.stderr,
            )
            return 1
        print(f"tokens/ up to date ({len(files)} files)")
        return 0

    TOKENS_DIR.mkdir(exist_ok=True)
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(files)} files to {TOKENS_DIR.relative_to(ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
